# Generated by Django 3.0.5 on 2020-05-07 17:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titleExtension', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('color', models.CharField(max_length=10)),
                ('numberOfPeople', models.IntegerField()),
                ('listOfRecipes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=20)),
            ],
        ),
    ]
